name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Node.js Setup
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      # Install dependencies and explicitly build React app
      - name: Install dependencies and build React app
        run: |
          cd roi-insightai-frontend
          npm install
          npm run build

      # Deploy to Azure Static Web Apps
      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          app_location: "/roi-insightai-frontend"
          output_location: "build"
